luku1 = int(input("Anna kokonaisluku: "))
luku2 = int(input("Anna toinen kokonaisluku: "))
print("Summa:", luku1 + luku2)
print("Erotus:", luku1 - luku2)
print("Tulo:", luku1 * luku2)
print("Osamäärä:", luku1 / luku2)